name: Build

on:
  push:
    branches:
      - main
jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to docker hub
      - name: Log in to Docker Hub with Access Token
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Build the docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-app-web:latest .

      # Step 5: Publish image to docker hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chat-app-web:latest
